version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BASE_URL=${BASE_URL}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - PG_USER=${PG_USER}
      - PG_HOST=postgres
      - PG_NAME=${PG_NAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=mysql
      - MYSQL_NAME=${MYSQL_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SQLITE_FILE=/app/url_shortener.db
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - mysql
      - redis
    volumes:
      - ./url_shortener.db:/app/url_shortener.db # For SQLite
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  mysql:
    image: mysql:8
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
  redis:
    image: redis:6
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
volumes:
  pgdata:
  mysqldata: